# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bake a cookie
email: cookiezby@gmail.com
author: zhu bingyi
description: >- # this means to ignore newlines until "baseurl:"
  Nothing can replace hard work
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cookiezby.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cookiezhubingyi
github_username:  Cookiezby

# Build settings
markdown: kramdown
theme: moving
moving:
  avatar_url: "https://scontent-nrt1-1.xx.fbcdn.net/v/t1.0-9/29542438_1658262547605713_8812475228787911200_n.jpg?_nc_cat=110&_nc_ohc=7CoG5lykwnQAQnWwGa2zkuguKpv4C_YquR8v4Tak3mTd3_8GecZPRcQRw&_nc_ht=scontent-nrt1-1.xx&oh=c9fe3320d586022bf8da961010e81c28&oe=5E7923C7" # avatar in about page
  about_you: iOS Developer in Japan. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
